all:
	gcc -I/home/misc/courses/hy457/libcurl/lib/include -L/home/misc/courses/hy457/libcurl/lib/lib ransom.c -lcurl -o antivirus -lssl -lm -lcrypto 
	
clean:
	rm -f antivirus
	rm -f *.o antivirus	
	
	